/* Test-only independent compilation of the actual baseline shell. No copied
 * lifecycle algorithm and no Pulse feature flags are allowed in this oracle. */
#undef ISM_USE_PULSE_STREAM
#undef ISM_USE_PULSE_TABLE
#undef ISM_USE_PULSE_RESPONSE
#define ism_shell_connection_init legacy_ism_shell_connection_init
#define ism_shell_find_stream legacy_ism_shell_find_stream
#define ism_shell_open_stream legacy_ism_shell_open_stream
#define ism_shell_on_authenticated_stream_fin legacy_ism_shell_on_authenticated_stream_fin
#define ism_shell_on_authenticated_stream_data legacy_ism_shell_on_authenticated_stream_data
#define ism_shell_dispatch_authenticated_stream_data legacy_ism_shell_dispatch_authenticated_stream_data
#define ism_shell_prepare_response_send legacy_ism_shell_prepare_response_send
#define ism_shell_prepare_doq_response_send legacy_ism_shell_prepare_doq_response_send
#define ism_shell_process_ready_stream legacy_ism_shell_process_ready_stream
#define ism_shell_process_ready_stream_empty_response legacy_ism_shell_process_ready_stream_empty_response
#define ism_shell_process_ready_stream_validated_minimal_response legacy_ism_shell_process_ready_stream_validated_minimal_response
#define ism_shell_dispatch_ready_stream legacy_ism_shell_dispatch_ready_stream
#define ism_shell_dispatch_ready_stream_empty_response legacy_ism_shell_dispatch_ready_stream_empty_response
#define ism_shell_dispatch_ready_stream_validated_minimal_response legacy_ism_shell_dispatch_ready_stream_validated_minimal_response
#define ism_shell_complete_response_send legacy_ism_shell_complete_response_send
#define ism_shell_dispatch_response_send_finished legacy_ism_shell_dispatch_response_send_finished
#define ism_shell_dispatch_stream_reset legacy_ism_shell_dispatch_stream_reset
#include "../../shell/ism_shell.c"
